spring:
  datasource:
    url: jdbc:h2:mem:resonancedb;DB_CLOSE_DELAY=-1
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.H2Dialect


